# Generated by Django 5.2.8 on 2025-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexusAPI', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
