# Generated by Django 5.2.8 on 2025-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexusAPI', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
